import React from "react";
import { Box, Typography, Card, CardContent, Grid } from "@mui/material";
import { motion } from "framer-motion";

const AboutPage = () => {
  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
        minHeight: "100vh",
        padding: "40px",
        backgroundColor: "#f4f6f9",
      }}
    >
      {/* Page Title */}
      <Typography variant="h3" gutterBottom component="div" sx={{ mb: 4 }}>
        About Our Project
      </Typography>

      {/* Animated Card */}
      <motion.div
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
      >
        <Card
          sx={{
            maxWidth: "800px",
            boxShadow: "0px 6px 15px rgba(0,0,0,0.2)",
            borderRadius: "16px",
          }}
        >
          <CardContent>
            {/* Project Overview */}
            <Typography
              variant="h6"
              sx={{ textAlign: "center", mb: 2, fontWeight: "bold" }}
            >
              Empowering Air Quality Insights
            </Typography>
            <Typography variant="body1" sx={{ mb: 2, textAlign: "justify" }}>
              This web application is designed to provide real-time insights
              into air quality and its potential impact on health. By leveraging
              advanced AI/ML models, the app offers users predictions and data
              visualizations to help them understand air quality trends.
            </Typography>
            <Typography variant="body1" sx={{ mb: 2, textAlign: "justify" }}>
              Our mission is to empower individuals and organizations with the
              tools they need to make informed decisions regarding air quality
              and public health. The data and predictions generated by this
              application can assist in better managing environmental health
              risks.
            </Typography>

            {/* Key Features */}
            <Typography
              variant="h6"
              sx={{ textAlign: "center", mt: 3, mb: 2, fontWeight: "bold" }}
            >
              Key Features:
            </Typography>
            <ul>
              <motion.li
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: 0.1 }}
              >
                Real-time air quality monitoring
              </motion.li>
              <motion.li
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: 0.2 }}
              >
                Health recommendations based on air quality
              </motion.li>
              <motion.li
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: 0.3 }}
              >
                Data visualization of historical air quality trends
              </motion.li>
              <motion.li
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: 0.4 }}
              >
                AI/ML-based predictions on air quality impacts
              </motion.li>
            </ul>

            {/* Technology Stack */}
            <Typography
              variant="body1"
              sx={{
                mt: 3,
                fontWeight: "bold",
                textAlign: "center",
                backgroundColor: "#e3f2fd",
                padding: "10px",
                borderRadius: "8px",
              }}
            >
              Technology Stack: React, Material-UI, FastAPI, Plotly.js
              and Machine Learning Model Integration.
            </Typography>
          </CardContent>
        </Card>
      </motion.div>
    </Box>
  );
};

export default AboutPage;
